version: "3.3"
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=security
    ports:
    - 3306:3306
    volumes:
    - /volumn/mysql/conf/:/etc/mysql/
    - /volumn/mysql/data:/var/lib/mysql
    - /volumn/mysql/mysql-files/:/var/lib/mysql-files
    command:
      mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp --skip-ssl --lower_case_table_names=1
