spring:
  application:
    name: security_test
  profiles:
    active: dev
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  messages:
    basename: messages
    encoding: UTF-8

logging:
 level:
   root: WARN
   com.example.demo: INFO
 pattern:
   console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
              %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

  
  
  # mvc:    
  #   throw-exception-if-no-handler-found: true
  # resources:
  #   add-mappings: false
# server.error.whitelabel.enabled: true