spring:
  application:
    name: security_test
  profiles:
    active: dev
    

# logging:
#   level:
    # root: WARN
    # com.example.demo: INFO
  messages:
    basename: messages

  
  
  # mvc:    
  #   throw-exception-if-no-handler-found: true
  # resources:
  #   add-mappings: false
# server.error.whitelabel.enabled: true