### 默认不配置SecurityConfit时，返回401
GET {{baseUrl}}/api/greeting HTTP/1.1
###
GET {{baseUrl}}/api/greeting HTTP/1.1
Authorization: Basic {{username}} {{password}}
### POST请求后面参数传递，需要禁用csrf，或者携带csrf token才能通过，否则是403——>401
POST {{baseUrl}}/api/greeting?name=何力 HTTP/1.1
AUthorization: Basic {{username}} {{password}}
### 
PUT {{baseUrl}}/api/greeting/何力 HTTP/1.1
AUthorization: Basic {{username}} {{password}}
### 
POST {{baseUrl}}/api/greeting?name=heli HTTP/1.1
AUthorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "name": "何力",
    "gender": "男"
}


###
### {{host}} 这种写法是rest-client配置在settings.json里面的环境变量,可以ctrl+shift+p: rest-client: switch environment改变环境
POST {{baseUrl}}/authorize/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###