###
POST {{host}}/authorize/register
Content-Type: application/json

{
    "name": "何力3",
    "username": "heli",
    "password": "aaaa",
    "matchPassword": "hl568H_L93j",
    "email": "568827302@qq.com"
}